version: '3'

services:
  app:
    restart: always
    build: .
    platform: linux/x86_64
    container_name: 'skill-matching'
    working_dir: '/workspace'
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8080:8888"
    tty: true
    volumes:
      - ./:/workspace
    networks:
      - db_network

networks:
  db_network:
    external: true